### PR TITLE
Fix urgent flag bug - model edition

### LINKED ISSUE #1203: Patients still marked urgent after pledge sent
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Need to revisit this because patients are still marked urgent after a pledge is sent. Refreshing the dash doesn't remove them.

* **What feature or behavior is this required for?**
My sanity

* **How could we solve this issue? (Not knowing is okay!)**
Looks like it has something to do with: https://github.com/DCAFEngineering/dcaf_case_management/pull/665

* **Anything else?**
screen shot 2017-08-15 at 8 57 36 pm

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Moves @tingaloo 's work in #1207  out of the controller and into the model.

This pull request makes the following changes:
* Fixes nightly urgent flag cleanup bug
* Checks urgent status on pledge sent so our CMs don't go nuts
* a little bit of tidying

It relates to the following issue #s: 
* Fixes #1203 
* stems from #1207 

@tingaloo can I get a review on this when you get a chance?

### CODE REVIEW

**Comment by colinxfleming** [comment]
bleh there's a stack error here. I'm going to revise some of our urgent processor code and come back to this tomorrow.

File: app/models/concerns/urgency.rb [hunk 1]
```diff
@@ -4,26 +4,26 @@ module Urgency
...
+    return false if recent_history_tracks.count.zero?
     return false if pledge_sent || resolved_without_fund
     recent_history_tracks.sort.reverse.each do |history|
       return true if history.marked_urgent?
     end
     false
   end
 
+  def confirm_still_urgent
+    update urgent_flag: false unless still_urgent?
```
Comment (tingaloo) [inline app/models/concerns/urgency.rb]: Here's the 🐛

File: app/models/patient.rb [hunk 2]
```diff
@@ -28,6 +28,7 @@ class Patient
   before_save :save_identifier
 
   after_create :initialize_fulfillment
+  after_save :confirm_still_urgent
```
Comment (tingaloo) [inline app/models/patient.rb]: I added this and i think it works, I'm guessing it is easier to control in the patient model than the module.
```
  before_save do
    self.urgent_flag = false unless still_urgent?
    true
  end
```

File: app/models/concerns/urgency.rb (hunk 1 above)
Comment (colinxfleming) [reply app/models/concerns/urgency.rb]: Oh, I think this was infinitely triggering the after_save callback somehow. Adding a conditional to check urgent status seems to fix it.

**Comment by colinxfleming** [comment]
@tingaloo 24432c2 should fix this up. Take a look when you have a sec?

**Comment by tingaloo** [comment]
Yup, it is that. 👍

**Comment by colinxfleming** [comment]
This has a bunch of legit test failures that I will now go thru.

**Comment by colinxfleming** [comment]
I think #1336 will fix the test failures here, so revisit after that

**Comment by colinxfleming** [comment]
There's a rerender issue here where the active partial is getting out of sync with the menu when it re-racks. This is relatively trivial in a javascript framework but kind of a pain here, and is such a specific minor bug that I'm going to elect to just not deal with it in here because I don't think it's worth the hassle.

File: app/views/patients/_menu.html.erb [hunk 3]
```diff
@@ -1,22 +1,19 @@
...
-    <li class='active'><%= link_to 'Patient Information', '#patient_information', data: { toggle: 'tab' } %></li>
-    <li><%= link_to 'Abortion Information', '#abortion_information', data: { toggle: 'tab' } %></li>
-    <li><%= link_to 'Notes', '#notes', data: { toggle: 'tab' } %></li>
-    <li><%= link_to 'Change Log', '#change_log', data: { toggle: 'tab' } %></li>
-    <li><%= link_to 'Call Log', '#call_log', data: { toggle: 'tab' } %></li>
-    <% if ( current_user.admin? || current_user.data_volunteer? ) && patient.pledge_sent == true %>
-      <li><%= link_to 'Pledge Fulfillment', '#fulfillment', data: { toggle: 'tab' } %></li>
-    <% end %>
+  <ul class="nav nav-pills nav-stacked" id='menu-list'>
+    <%= render 'menu_item', link_for: 'patient_information', active: true %>
```
Comment (colinxfleming) [inline app/views/patients/_menu.html.erb]: Moved this to a partial so we can more surgically rerender this, instead of flattening it.

File: app/views/patients/update.js.erb [hunk 4]
```diff
@@ -1,44 +1,45 @@
-// rerack approx gestation
-<% if @patient.previous_changes.present? %>
-  $('#patient_appointment_date')
-    .parent()
-    .find('span.help-block')
-    .text('Approx gestation at appt: <%= @patient.last_menstrual_period_at_appt %>');
+// rerack fields
+$('#patient_appointment_date')
```
Comment (colinxfleming) [inline app/views/patients/update.js.erb]: The callback wipes `previous_changes`, so we had to rewire this a little (a lot). Now it just rerenders everything after save regardless.
