### PR TITLE
Fix dashboard N+1 queries

### LINKED ISSUE #1054: Eliminate n+1 query on call list
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
The top two pieces of the call list, `Your call list` and `Completed calls` (populated by `current_user.ordered_patients(current_line)` and `current_user.recently_called_patients(current_line)` respectively) are loading via individual finds. We should try to make this one query per partial, so it behaves more like the urgent patients partial (which is a simple, singular `{"find"=>"patients", "filter"=>{"_line"=>{"$in"=>[:DC]}, "urgent_flag"=>true}}`).

* **What feature or behavior is this required for?**
Page load optimizing, good db practice, keeping things feeling snappy, clean code.

* **How could we solve this issue? (Not knowing is okay!)**
Likely the answer here involves wrenching on `ordered_patients` and `recently_called_patients` to give those methods a sense of patients as a collection rather than a set of individual entries. (In other words, probably edit the methods to do the db call in there.)

* **Anything else?**
nope!

### PR DESCRIPTION
**Pull request by tingaloo**
I rule and have completed some work on Case Manager that's ready for review!

Optimized dashboard mongo queries.

This pull request makes the following changes:
call lists, etc should be snappy.

It relates to the following issue #s: 
* Fixes #1054

### CODE REVIEW

**Comment by tingaloo** [comment]
In ```dashboards/index.html```, there's a @urgent_patients call. However this same call breaks at ```refresh_patients.js.erb ``` and ```calls_create.js```. I'm just curious if @urgent_calls needs to exist, because i'm not sure of its purpose within module ```Urgency```

**Comment by tingaloo** [comment]
@colinxfleming pinging for a review, this should be working.

**Comment by tingaloo** [comment]
Reminding myself to modify calls if enum library ever gets pushed.

File: app/models/user.rb [hunk 1]
```diff
@@ -102,13 +102,9 @@ def self.from_omniauth(access_token)
...
 
   def recently_called_patients(lines = LINES)
-    patients.in(_line: lines)
-            .select { |patient| recently_called_by_user? patient }
-  end
-
-  def call_list_patients(lines = LINES)
-    patients.in(_line: lines)
-            .reject { |patient| recently_called_by_user? patient }
+    Patient.in(_line: lines, user_ids: BSON::ObjectId(id)).where( :$and =>
```
Comment (colinxfleming) [inline app/models/user.rb]: I think the inclination here is really powerful (filtering on the db level, rather than the others)! I think that's a great insight.

I'd like to confirm that the number of db calls here reduces. I think when we wrote this we were trying to take advantage of some result caching by executing basically the same query twice (`patients.in(_line: lines)`), but that didn't quite pan out. Can we compare logs from the rails console in this PR to confirm stuff is cooking the way we want it to?

File: app/models/user.rb [hunk 2]
```diff
@@ -102,13 +102,9 @@ def self.from_omniauth(access_token)
...
+    [ { :"calls.updated_at"  => (8.hours.ago..Time.now) },
```
Comment (colinxfleming) [inline app/models/user.rb]: two things here: 

a) let's set 8.hours.ago to a constant of some kind, and swap this out. Makes it a little more readable imo
b) we'll want `Time.zone.now` rather than just `Time.now`. Time zones are, as always, actual hell on earth, but ruby's time objects has a lot of good ways around it.

File: app/models/user.rb [hunk 3]
```diff
@@ -134,10 +130,16 @@ def reorder_call_list(order)
 
   def ordered_patients(lines = LINES)
     return call_list_patients(lines) unless call_order
-    ordered_patients = call_list_patients(lines).sort_by do |patient|
-      call_order.index(patient.id.to_s) || call_order.length
-    end
-    ordered_patients
+      ordered_patients = call_list_patients(lines).sort_by do |patient|
```
Comment (colinxfleming) [inline app/models/user.rb]: do me a solid and undo this indent? Doesn't look like anything changed here

File: app/models/user.rb (hunk 1 above)
Comment (tingaloo) [inline app/models/user.rb]: Here's what I gathered based on the initial DB call.

original call
```
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('5950a1542cde110a61906299'), BSON::ObjectId('5950a1542cde110a6190629d'), BSON::ObjectId('5950a1542cde110a619062a1'), BSON::ObjectId('5950a1542cde110a619062a5'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.010525s
```

With the new DB calls
```
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"_line"=>{"$in"=>[:DC]}, "user_ids"=>{"$in"=>[BSON::ObjectId('5950a1532cde110a6190628b')]}, "$and"=>[{"calls.updated_at"=>{"$ne"=>{"$gte"=>2017-06-25 22:03:00 UTC, "$lte"=>2017-06-26 06:03:00 UTC}}}, {"calls.created_by_...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.007338000000000001s
```

There looks to be a difference of 1 significant figure, so that's 👍

**Comment by tingaloo** [comment]
I only tested this against the development seeds and it seems to work. Need a second pair of eyes to verify if the same call list displays.

**Comment by colinxfleming** [comment]
Looks like this breaks completed calls functionality as is, so we'll want to dig into that a little bit. 

Logs from this branch, with mostly fresh seed data and logging a call on pt 0 and pt 1:

```
Started GET "/" for ::1 at 2017-06-28 18:51:44 -0400
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"sessions", "filter"=>{"_id"=>"9dd733a96090f96b56a3ffe78b61f27d"}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.001215s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>BSON::ObjectId('595432ac311c8884230e4ca1')}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.001675s
Processing by DashboardsController#index as HTML
  Rendering dashboards/index.html.erb within layouts/application
  Rendered dashboards/_budget_bar.html.erb (2.7ms)
  Rendered dashboards/_search_form.html.erb (4.7ms)
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"_line"=>{"$in"=>[:DC]}, "user_ids"=>{"$in"=>[BSON::ObjectId('595432ac311c8884230e4ca1')]}, "calls.updated_at"=>{"$ne"=>{"$gte"=>2017-06-28 14:47:15 UTC, "$lte"=>2017-06-28 22:47:15 UTC}}}, "sort"=>{"created_at"=>-1}}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.009793s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.011499s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.009868s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.011884s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.011302s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.012237s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.013154s
  Rendered dashboards/_table_content.html.erb (109.3ms)
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"_line"=>{"$in"=>[:DC]}, "user_ids"=>{"$in"=>[BSON::ObjectId('595432ac311c8884230e4ca1')]}, "$and"=>[{"calls.updated_at"=>{"$gte"=>2017-06-28 14:47:15 UTC, "$lte"=>2017-06-28 22:47:15 UTC}}, {"calls.created_by_id"=>BSON...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.000954s
  Rendered dashboards/_table_content.html.erb (3.1ms)
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"_line"=>{"$in"=>[:DC]}, "urgent_flag"=>true}}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.009354000000000001s
  Rendered dashboards/_table_content.html.erb (33.7ms)
  Rendered dashboards/_modal.html.erb (0.4ms)
  Rendered dashboards/index.html.erb within layouts/application (178.8ms)
  Rendered layouts/_navigation_links.html.erb (2.8ms)
  Rendered layouts/_navigation.html.erb (7.1ms)
  Rendered layouts/_messages.html.erb (1.1ms)
  Rendered layouts/_footer.html.erb (2.9ms)
Completed 200 OK in 725ms (Views: 721.0ms)
```
8 queries to patients not counting urgents, 6 patients on the call list

from master:

```
Started GET "/" for ::1 at 2017-06-28 18:52:58 -0400
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"sessions", "filter"=>{"_id"=>"9dd733a96090f96b56a3ffe78b61f27d"}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.003682s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>BSON::ObjectId('595432ac311c8884230e4ca1')}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.0041340000000000005s
Processing by DashboardsController#index as HTML
  Rendering dashboards/index.html.erb within layouts/application
  Rendered dashboards/_budget_bar.html.erb (3.6ms)
  Rendered dashboards/_search_form.html.erb (9.0ms)
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.012700999999999999s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.014780000000000001s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.037278s
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.017327s
  Rendered dashboards/_table_content.html.erb (136.8ms)
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"$and"=>[{"_id"=>{"$in"=>[BSON::ObjectId('595432ae311c8884230e4caf'), BSON::ObjectId('595432ae311c8884230e4cb3'), BSON::ObjectId('595432ae311c8884230e4cb7'), BSON::ObjectId('595432ae311c8884230e4cbb'), BSON::ObjectId('5...
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.029676s
  Rendered dashboards/_table_content.html.erb (106.9ms)
MONGODB | localhost:27017 | dcaf_case_management_development.find | STARTED | {"find"=>"patients", "filter"=>{"_line"=>{"$in"=>[:DC]}, "urgent_flag"=>true}}
MONGODB | localhost:27017 | dcaf_case_management_development.find | SUCCEEDED | 0.010969000000000001s
  Rendered dashboards/_table_content.html.erb (52.5ms)
  Rendered dashboards/_modal.html.erb (1.0ms)
  Rendered dashboards/index.html.erb within layouts/application (419.2ms)
  Rendered layouts/_navigation_links.html.erb (3.7ms)
  Rendered layouts/_navigation.html.erb (10.0ms)
  Rendered layouts/_messages.html.erb (0.7ms)
  Rendered layouts/_footer.html.erb (2.2ms)
Completed 200 OK in 2912ms (Views: 2776.4ms)

```
5 queries to patients not counting urgents, 6 patients on call list.

I think by starting both queries with `patients.in(_line ...) and then doing a select in memory from there, rails is caching the result for later, whereas it isn't with the change. This is really weird though. Is it checking some reference or something?

**Comment by tingaloo** [comment]
This makes no sense. From master, I guess the entire patient list gets loaded up initially. I still don't get why it'd be queried so many times. I'm no mongo expert so I'm not sure what to make of these logs, I'll probably just drop this..

**Comment by colinxfleming** [comment]
leave 'er open for now and let's poke at this over the weekend. I have a hunch.
