### PR TITLE
fix modal load

### LINKED ISSUE #1089: Turbolinks issue on pledge modal
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
It is with a heavy heart that I must inform us that our enemy turbolinks is at it again. The issue that had us stuck on version 2 or whatever, the pledge modal loading empty when nothing's happened on a page yet, has reared its ugly head again.

Steps to recreate:

* `rake db:seed`
* log in to app
* click on patient `Clinic and Appt - 2` in call log
* click on 'Submit Pledge'
* oh no!

screen shot 2017-06-03 at 11 34 37 am

* update the `Appointment date` field - increment a day, do something to trigger the onChange action/get some javascript to fire
* Click on 'Submit Pledge' again and see it show up now (it's cancel pledge for me, but the point is the modal has data):

screen shot 2017-06-03 at 11 40 23 am

* **What feature or behavior is this required for?**
Pretty core functionality of sending pledges, so we should prioritize resolution and not deploy this Sunday until this is fixed, if possible. 

* **How could we solve this issue? (Not knowing is okay!)**
Adjust the magic turbolinks switch, I assume. We should also add an integration test for this particular case, if possible, since it's bitten us in the behind a few times.

* **Anything else?**
@tingaloo you around to give this a fixer upper?

### PR DESCRIPTION
**Pull request by tingaloo**
I rule and have completed some work on Case Manager that's ready for review!

Fix submit pledge modal, this was pushed before the turbolinks merge so that'd explain the failure of modal steps populating.

This pull request makes the following changes:
* Added turbolinks loader

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #1089

### CODE REVIEW

**Comment by colinxfleming** [comment]
MY DUDE

Can you merge that failing test in #1091 into here so we can confirm it blends properly?

**Comment by colinxfleming** [comment]
This fixes the issue in #1089 and the test failures are due to flakiness. I'm merging.

File: app/assets/javascripts/external_pledges.coffee [hunk 1]
```diff
@@ -4,6 +4,6 @@
 
 jQuery ->
   # use event that works with rails turbolinks
-  $(document).on 'ready page:load', ->
+  $(document).on 'turbolinks:load', ->
```
Comment (colinxfleming) [inline app/assets/javascripts/external_pledges.coffee]: ALWAYS SOMETHING WITH THESE TURBOLINKS
