### PR TITLE
Fix urgent flag bug

### LINKED ISSUE #1203: Patients still marked urgent after pledge sent
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Need to revisit this because patients are still marked urgent after a pledge is sent. Refreshing the dash doesn't remove them.

* **What feature or behavior is this required for?**
My sanity

* **How could we solve this issue? (Not knowing is okay!)**
Looks like it has something to do with: https://github.com/DCAFEngineering/dcaf_case_management/pull/665

* **Anything else?**
screen shot 2017-08-15 at 8 57 36 pm

### PR DESCRIPTION
**Pull request by tingaloo**
I rule and have completed some work on Case Manager that's ready for review!

On pledge submit, automatically removes urgent flag.
On pledge rescind, check if @patient.resolved_without_fund. If resolved, removes urgent flag.

I'm not really sure about the urgent flag flow, but i'm throwing this out there.

This pull request makes the following changes:
* Fix urgent flag

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #1203 
* Bumps #Y

### CODE REVIEW

File: app/views/patients/update.js.erb [hunk 1]
```diff
@@ -27,6 +27,7 @@
     $('#sections').append(
       '<%= escape_javascript(render partial: "patients/fulfillment", locals: { patient: @patient })%>'
     );
+    <% @patient.update_attributes urgent_flag: false %>
```
Comment (colinxfleming) [inline app/views/patients/update.js.erb]: The idea here is dead on, but can we put this into the patients controller? Specifically, I'd like to see this happen as part of the update action -- we don't want to change object state in our views if we can possibly avoid it.

**Comment by tingaloo** [comment]
I'm not sure if it is updating when I place it in ```patients#update```, can you verify?

File: app/controllers/patients_controller.rb [hunk 2]
```diff
@@ -59,8 +59,30 @@ def edit
...
+  #     end
+  #   end
+  #   return patient
+  # end
+
   def update
     if @patient.update_attributes patient_params
+      # @patient = update_urgent_flag(patient)
+      @patient.reload
+      if @patient.pledge_sent?
```
Comment (colinxfleming) [inline app/controllers/patients_controller.rb]: The core of this is pretty sound and looks good to me. I'm gonna hook this into an `after_save` callback on the Patient model -- seems dicey to me to put this in the controller layer, which is generally responsible for responding to http calls or whatever. (And probably add a test along the way!)
