### PR TITLE
handle cases when patients get detached from call list entries

### LINKED ISSUE #2125: patient dashboard bug: undefined method `calls' for nil:NilClass for some reason
Sentry Issue: [DARIA-1G](https://sentry.io/organizations/dcaf-engineering/issues/2211128563/?referrer=github_integration)

```
NoMethodError: undefined method `calls' for nil:NilClass
  app/models/concerns/call_listable.rb:85:in `recently_called_by_user?'
    patient.calls.any? { |call| call.created_by_id == id && call.recent? }
  app/models/concerns/call_listable.rb:11:in `block in call_list_patients'
    ordered_patients(line).reject { |x| recently_called_by_user? x }
  app/models/concerns/call_listable.rb:11:in `reject'
    ordered_patients(line).reject { |x| recently_called_by_user? x }
  app/models/concerns/call_listable.rb:11:in `call_list_patients'
    ordered_patients(line).reject { |x| recently_called_by_user? x }
  app/views/dashboards/index.html.erb:14:in `_app_views_dashboards_index_html_erb__4189443243028251790_35660'
    patients: current_user.call_list_patients(current_line),
...
(137 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `calls' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Small unexpected bug around patients being in flight. I have no idea why this happened and why it wasn't handled by callbacks, but worth doing regardless.

This pull request makes the following changes:
* clean orphaned call list 
* add a safety check to pulling order call lists, to filter out anything detached on the spot

no view changes

It relates to the following issue #s: 
* Fixes #2125 

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

File: test/models/user_test.rb [hunk 1]
```diff
@@ -64,6 +64,11 @@ class UserTest < ActiveSupport::TestCase
       assert_equal 1, @user.call_list_patients('DC').count
     end
 
+    it 'should not fail if a patient gets unattached from the call list' do
+      @user.call_list_entries.where(line: 'DC').first.update patient: nil
```
Comment (rudietuesdays) [inline test/models/user_test.rb:68]: Is this specific to the DC line, or should it echo this behavior for MD and VA? (Or is it the same behavior; do we only need to test DC?)

**Review by rudietuesdays — APPROVED** [review]
LGTM! Wondering about if we need duplicate tests for MD and VA, and if not this is good to go

File: test/models/user_test.rb (hunk 1 above)
Comment (colinxfleming) [reply test/models/user_test.rb:68]: oh, this is just particular to the way we bootstrap this test (it also includes a MD line), but I guess it shouldn't matter since we're using assert diff. Fixing, thanks for this catch!
