### PR TITLE
Fix Tablesort after Search Bug

### LINKED ISSUE #1099: Stupidtable Sort does not work after Search
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
In ```users/index.html.erb```, stupidtable sort does not work after search

* **What feature or behavior is this required for?**
It's a bug.

* **How could we solve this issue? (Not knowing is okay!)**
Something about javascript and turbolinks?

* **Anything else?**
See #1073

### PR DESCRIPTION
**Pull request by tingaloo**
I rule and have completed some work on Case Manager that's ready for review!

Fix sorting by date after searching for a user.
A not so neat hack by calling the entire autosort function after a search completes. There might be a better way calling a javascript function elsewhere but I forget how to do so.

This pull request makes the following changes:
* Call autosorting table after search.js.erb dispatches

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #1099 
* Bumps #Y

### CODE REVIEW

File: app/assets/javascripts/table_sorting.coffee [hunk 1]
```diff
@@ -2,18 +2,21 @@
...
+ready = ->
+  # make the columns of all of the tables sortable
+  sortTables()
+$(document).on 'ready page:load', ready
 
-        # when a column is clicked, make sure to reset all of the other columns back to [-]
-        stupidtable.on 'beforetablesort', ( event, data ) ->
-            stupidtable.find( 'th' ).filter( ( i ) -> return i isnt data.column ).find( '.arrow' ).html( '[-]' )
+sortTables = ->
+  autosortable_tables = [ '#call_list table', '#completed_calls table', '#urgent_patients table', '#user-list table']
```
Comment (colinxfleming) [inline app/assets/javascripts/table_sorting.coffee]: Should probably make this a class rather than doing it by ids, no?

File: app/views/users/search.js.erb [hunk 2]
```diff
@@ -1,6 +1,26 @@
 
 <% if @results.any? %>
-  $('#user-list').html("<%= escape_javascript(render partial: 'users/users_table', locals: { users: @results }) %>");
+  $('#user-list').html("<%= escape_javascript(render partial: 'users/users_table', locals: { users: @results, autosortable: true }) %>");
+
+  //TODO figure out way to import function from /javascripts/table_sorting.coffee
```
Comment (colinxfleming) [inline app/views/users/search.js.erb]: So I checked and I think this is a problem in table content on the dashboard after we add or remove a user, too. I wonder if we can move the stupidtable invocation to its own partial (something like `app/views/shared/_activate_stupidtable.js.erb`) and drop in something like `<%= render partial: shared/activate_stupidtable %>`?

Comment (tingaloo) [reply app/views/users/search.js.erb]: Don't know where the edge cases are but I made the partial for rendering.

File: app/assets/javascripts/table_sorting.coffee [hunk 3]
```diff
@@ -2,18 +2,19 @@
 # All this logic will automatically be available in application.js.
 # You can use CoffeeScript in this file: http://coffeescript.org/
 
-jQuery ->
-  $(document).on 'ready page:load', ->
-    # make the columns of all of the tables sortable
-    autosortable_tables = [ '#call_list table', '#completed_calls table', '#urgent_patients table', '#user-list table']
-    autosortable_tables.forEach ( table ) ->
-        stupidtable = $( table ).stupidtable()
+$(document).on 'turbolinks:load', ->
```
Comment (tingaloo) [inline app/assets/javascripts/table_sorting.coffee]: This fixes a bug when you navigate between pages and the stupidtable no longer works.

File: app/assets/javascripts/table_sorting.coffee [hunk 4]
```diff
@@ -2,18 +2,19 @@
...
 
-        # when a column is clicked, make sure to reset all of the other columns back to [-]
-        stupidtable.on 'beforetablesort', ( event, data ) ->
-            stupidtable.find( 'th' ).filter( ( i ) -> return i isnt data.column ).find( '.arrow' ).html( '[-]' )
-
-        # when a column is clicked, show an up or down arrow appropriately
-        stupidtable.on 'aftertablesort', ( event, data ) ->
-            arrow = if data.direction is $.fn.stupidtable.dir.ASC then '[&uarr;]' else '[&darr;]'
-            stupidtable.find( 'th' ).eq( data.column ).find( '.arrow' ).html( arrow )
+sortTables = ->
```
Comment (colinxfleming) [inline app/assets/javascripts/table_sorting.coffee]: Fun fact I learned after poking at coffeescript recently: You can export functions by slapping an `@` in front of em. Kinda nice! (This is good as is though.)
