### PR TITLE
Has Special Circumstance Always Returns True

### LINKED ISSUE #1827: CSV Export shows all TRUE for special circumstances
* **What are we trying to do?**
Our CSV export provides a limited about of anonymized information, including a boolean field specifying whether the patient had any Special Circumstances checked under Patient Information. But right now it is exporting TRUE for everyone, regardless of whether there are any checked.

 - Fix the CSV export to properly export `has special circumstances`
 - Update our tests to check that!

To reproduce, click the admin dropdown in the upper right and click 'Export anonymized CSV'

* **What feature or behavior is this required for?**
BRAF bug request!

### PR DESCRIPTION
**Pull request by ChrisBarthol**
I rule and have completed some work on Case Manager that's ready for review!

The `has_special_circumstance` method was always returning true to boolean safety checks against ints.

```
irb(main):001:0> !!0
=> true
irb(main):002:0> !!1
=> true
irb(main):003:0> !!false
=> false
irb(main):004:0> !!true
=> true
```

This pull request makes the following changes:
* switched from `0` and `1` to `true` and `false`
* added a test

It relates to the following issue #s: 
* Fixes #1827

### CODE REVIEW

**Comment by colinxfleming** [comment]
Checks out! Thank you much @chrisbarthol, glad this was an easy fix. I will review in more depth later this wknd.

File: app/models/patient.rb [hunk 1]
```diff
@@ -246,9 +246,9 @@ def notes_count
   end
 
   def has_special_circumstances
-    has_circumstance = 0
+    has_circumstance = false
```
Comment (colinxfleming) [inline app/models/patient.rb]: This is great! I think we got tripped up by the handling here and what ruby considers truthy.

@ChrisBarthol what do you think about simplifying this a little? The variable assignment and then boolean casting is kinda tricky. Maybe something like this would work?

`special_circumstances.map { |x| x.present? }.any?`

That would cast each of the special circumstances to true or false, and then return true if there are any trues or false otherwise. Ex:

```
irb(main):001:0> [false, true, true].any? 
=> true
irb(main):002:0> [false, false, false].any? 
=> false
```

what do you think?

Comment (ChrisBarthol) [reply app/models/patient.rb]: Great catch on the simplification!  Switched to map and added a few extra test cases.

**Comment by colinxfleming** [comment]
thank you very much @ChrisBarthol !
